######################## default configuration ####################
# baseURL = "https://docs.amperfii.io/"
baseURL = "http://anutry.com.s3-website.us-east-2.amazonaws.com/"
title = "Amperfii Knowledge Base"
theme = "godocs-hugo-1"
# disable lang
disableLanguages = [] # desable language from here


[[deployment.targets]]
# An arbitrary name for this target.
name = "awsbucket"
URL = "s3://anutry.com/?region=us-east-2" #your bucket here

# hugo outputs
[outputs]
home = [ "HTML", "RSS", "JSON"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/search/auto-complete.css"
[[params.plugins.css]]
link = "plugins/featherlight/featherlight.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.min.js"
[[params.plugins.js]]
link = "plugins/featherlight/featherlight.min.js"
[[params.plugins.js]]
link = "plugins/clipboard/clipboard.min.js"
[[params.plugins.js]]
link = "plugins/match-height/jquery.matchHeight-min.js"
[[params.plugins.js]]
link = "plugins/search/auto-complete.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/search/lunr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search-page.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Company"
url = "https://amperfii.com"
weight = 1


# footer menu
[[menu.footer]]
name = "Changelog"
url = "changelog"
weight = 1

[[menu.footer]]
name = "Contact"
url = "contact"
weight = 2



#################### default parameters ################################
[params]
#logo = "images/logo.png"
logo = "images/amperfii-med.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button bordered
[params.navigation_button_bordered]
enable = true
label = "changelog"
link = "changelog"

# Navigation button solid
[params.navigation_button_solid]
enable = true
label = "contact"
link = "contact"

  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
# copyright
#copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
copyright = "Copyright &copy; 2020  [Amperfii](https://amperfii.com)"

#   
[Languages.en.banner]
title = "Amperfii Knowledge Base"
subtitle = "Lorem ipsum dolor amet, consetetur sadiffspscing elitr, diam nonumy invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua At."
image = "images/banner_color.png"

# call to action
[Languages.en.call_to_action]
enable = true
title = "Still Didn't Find Your Answer?"
image = "images/cta-illustration.jpg"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam <br> nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"

  # call to action button
  [Languages.en.call_to_action.button]
  enable = "true"
  label = "Send us you query"
  link = "contact"


###################################
[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "aws"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
# URL = "gs://<Bucket Name>"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
 URL = "s3://docs.amperfii.io?region=ap-southeast-2"

# Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
# URL = "azblob://$web"

# You can use a "prefix=" query parameter to target a subfolder of the bucket:
# URL = "gs://<Bucket Name>?prefix=a/subfolder/"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "E15YVOUUQKA55W"

# Optionally, you can include or exclude specific files.
# See https://godoc.org/github.com/gobwas/glob#Glob for the glob pattern syntax.
# If non-empty, the pattern is matched against the local path.
# All paths are matched against in their filepath.ToSlash form.
# If exclude is non-empty, and a local or remote file's path matches it, that file is not synced.
# If include is non-empty, and a local or remote file's path does not match it, that file is not synced.
# As a result, local files that don't pass the include/exclude filters are not uploaded to remote,
# and remote files that don't pass the include/exclude filters are not deleted.
# include = "**.html" # would only include files with ".html" suffix
# exclude = "**.{jpg, png}" # would exclude files with ".jpg" or ".png" suffix


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# Samples:

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true